# Change these first
owner: HeliosCompliance # Your GitHub organization or username, where this repository lives
repo: upptime-pocket # The name of this repository

sites:
  - name: PayByPocket
    url: https://paybypocket.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.paybypocket.com
  # baseUrl: /your-repo-name
  logoUrl: https://paybypocket.com/assets/paybypocketLogo-1ac854be.svg
  name: PayByPocket Status
  introTitle: "PayByPocket Status Page"
  introMessage: Live system availability and incident updates for PayByPocket.
  navbar:
    - title: Status
      href: /
    - title: Incident History
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
